{
 "title": "网站监控",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "im网站状态码监控",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "生产环境ping网络监控",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"network-monitor\"}",
     "legendFormat": "{{group}} {{ping}}"
    }
   ]
  },
  {
   "title": "im网站访问速度监控",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "probe_http_duration_seconds", "legendFormat": "{{instance}} {{phase}}" }
   ]
  },
  {
   "title": "mysql监控",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_binlog_bytes_written{instance=\"112db\",job=\"mysql\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "mysql_global_status_connections",
     "legendFormat": "{{host}} connections"
    }
   ]
  }
 ]
}